#!/usr/bin/env python3
"""
mouse_statistics.py - Calculate dataset-wide statistics for model training.

This script scans a directory of SQLite databases generated by `extract.py`
to compute normalization parameters.

CORRECTED VERSION: This script now correctly simulates the data merging logic
from `injection_mold.py`. It fetches per-tick data and then sums the mouse
deltas for consecutive ticks (tick and tick+1) for each player before
calculating the final statistics. This ensures the normalization parameters
perfectly match the data format consumed by the model during training.

Usage:
    python mouse_statistics.py --db-dir /path/to/your/data/db
"""

import argparse
import sqlite3
import logging
from pathlib import Path
from collections import defaultdict

import numpy as np
from tqdm import tqdm

# --- Setup Logging ---
logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')

def get_mouse_data_map_from_db(db_path: Path) -> dict:
    """
    Connects to a single SQLite database and extracts mouse data into a
    fast lookup map.

    Args:
        db_path: The path to the .db file.

    Returns:
        A dictionary mapping (playername, tick) to (mouse_x, mouse_y).
    """
    mouse_data_map = {}
    conn = None
    try:
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        cursor = conn.cursor()
        
        query = "SELECT playername, tick, mouse_x, mouse_y FROM player WHERE mouse_x IS NOT NULL AND mouse_y IS NOT NULL"
        
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='player';")
        if cursor.fetchone() is None:
            logging.warning(f"Table 'player' not found in {db_path}. Skipping.")
            return {}

        cursor.execute(query)
        
        for row in cursor.fetchall():
            playername, tick, mx, my = row
            mouse_data_map[(playername, tick)] = (mx, my)

    except sqlite3.Error as e:
        logging.error(f"Failed to process database {db_path}: {e}")
        return {}
    finally:
        if conn:
            conn.close()
            
    return mouse_data_map


def main():
    """Main function to find DBs, aggregate data, and compute stats."""
    parser = argparse.ArgumentParser(
        description="Calculate normalization stats from CS2 data databases with tick merging."
    )
    parser.add_argument(
        "--db-dir",
        required=True,
        type=Path,
        help="Directory to recursively search for .db files."
    )
    args = parser.parse_args()

    if not args.db_dir.is_dir():
        logging.error(f"Error: Provided path is not a directory: {args.db_dir}")
        return

    logging.info(f"Scanning for .db files in '{args.db_dir}'...")
    db_files = list(args.db_dir.rglob("*.db"))

    if not db_files:
        logging.error(f"No .db files found in '{args.db_dir}'. Please check the path.")
        return

    logging.info(f"Found {len(db_files)} database file(s). Processing...")

    # This map will store all data from all databases
    full_mouse_data_map = {}
    for db_path in tqdm(db_files, desc="Loading data from DBs"):
        db_map = get_mouse_data_map_from_db(db_path)
        full_mouse_data_map.update(db_map)

    if not full_mouse_data_map:
        logging.error("No valid mouse data was found across all databases.")
        return

    logging.info("Simulating two-tick merge before calculating stats...")

    # Group ticks by player for efficient processing
    player_ticks = defaultdict(list)
    for playername, tick in full_mouse_data_map.keys():
        player_ticks[playername].append(tick)
    
    # Sort ticks for each player to ensure correct sequential processing
    for player in player_ticks:
        player_ticks[player].sort()

    merged_mouse_x, merged_mouse_y = [], []
    
    # Iterate through each player and their sorted ticks
    for player, ticks in tqdm(player_ticks.items(), desc="Merging ticks"):
        for tick in ticks:
            # Check if the next consecutive tick exists for this player
            next_tick = tick + 1
            if (player, next_tick) in full_mouse_data_map:
                # Perform the sum, just like injection_mold.py
                current_mx, current_my = full_mouse_data_map[(player, tick)]
                next_mx, next_my = full_mouse_data_map[(player, next_tick)]
                
                merged_mx = current_mx + next_mx
                merged_my = current_my + next_my
                
                merged_mouse_x.append(merged_mx)
                merged_mouse_y.append(merged_my)

    if not merged_mouse_x:
        logging.error("No consecutive ticks found to merge. Cannot calculate statistics.")
        return

    # Convert to NumPy arrays for efficient computation
    mouse_x_np = np.array(merged_mouse_x, dtype=np.float64)
    mouse_y_np = np.array(merged_mouse_y, dtype=np.float64)

    # Calculate statistics on the MERGED data
    mean_x = np.mean(mouse_x_np)
    std_x = np.std(mouse_x_np)
    mean_y = np.mean(mouse_y_np)
    std_y = np.std(mouse_y_np)
    
    total_points = len(mouse_x_np)

    # --- Print Results ---
    print("\n" + "="*70)
    print("      Dataset-Wide Mouse Normalization Stats (After 2-Tick Merge)")
    print("="*70)
    print(f"\nProcessed {len(db_files)} file(s) generating {total_points:,} valid merged data points.")
    print(f"\nMouse X -> Mean: {mean_x:10.6f} | Std Dev: {std_x:10.6f}")
    print(f"Mouse Y -> Mean: {mean_y:10.6f} | Std Dev: {std_y:10.6f}")

    print("\n" + "-"*70)
    print("ACTION REQUIRED: Copy the following code block into your `train2.py`")
    print("file, replacing the placeholder values in the `BatchAssembler` class.")
    print("-" * 70)
    print("\033[92m") # Start green text
    print(f"# --- In train2.py, inside BatchAssembler.assemble ---")
    print(f"# Calculated from {len(db_files)} game(s) with {total_points:,} merged data points.")
    print(f'MOUSE_DELTA_MEAN = torch.tensor([{mean_x:.6f}, {mean_y:.6f}], device=self.device)')
    print(f'MOUSE_DELTA_STD = torch.tensor([{std_x:.6f}, {std_y:.6f}], device=self.device)')
    print("\033[0m") # End green text
    print("="*70)


if __name__ == "__main__":
    main()