services:
  dev:
    image: pytorch/pytorch:2.9.1-cuda12.8-cudnn9-devel
      #image: pytorch/pytorch:2.10.0-cuda13.0-cudnn9-devel
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - /mnt/trainingdata/dataset0/:/workspace/dataset0
      - /mnt/trainingdata/sampledata/:/workspace/data
      - pip-cache:/root/.cache/pip

      # Unified cache for Hugging Face
      - ./cache/hf:/workspace/.cache/huggingface
      # Torch / timm / torch.hub cache
      - ./cache/torch:/workspace/.cache/torch
    ports:
      - "8080:8080"             # model3 runtime UI
      - "127.0.0.1:6006:6006"   # TensorBoard (localhost only)
      - "127.0.0.1:8888:8888" # (optional) Jupyter (localhost only)
    stdin_open: true
    tty: true
    ipc: host
    shm_size: "16gb"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

      # Hugging Face unified home
      - HF_HOME=/workspace/.cache/huggingface
      # Optional: separate datasets cache (otherwise goes into HF_HOME)
      - HF_DATASETS_CACHE=/workspace/.cache/huggingface/datasets
      # Torch hub cache (used by timm & torch.hub)
      - TORCH_HOME=/workspace/.cache/torch

    gpus: all
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "apt update -y && apt upgrade -y && apt install libgl1 ffmpeg -y && python -m pip install --break-system-packages --upgrade pip setuptools wheel &&
       if [ -f requirements.txt ]; then pip install --break-system-packages -r requirements.txt; fi && 
       pip install --break-system-packages -r requirements2.txt && MAX_JOBS=16 pip install --break-system-packages flash-attn --no-build-isolation &&
       echo '✅ Environment ready. Caches are mounted at HF_HOME and TORCH_HOME.' &&
       exec bash"

volumes:
  pip-cache:
